### ISSUE TITLE
Next version todo/changelog

### ISSUE THREAD

**Issue by TrySound** [css-modules/css-modules#240]
Here's changes I made last time and TODO for near future

## keyframes
- [x] always local if plugin is enabled
- [x] animation name is replaced with existing local keyframes or leaved untouched
- [x] add warnings when keyframes identifier already declared by different plugin
- [x] disallow all reserved names without checking count of usage (`animation: infinite infinite`). Was made to improve performance and reduce implementation complexity. Should we revert this?

## local-by-default
- [x] split keyframes in separate package
- [ ] rename to `postcss-icss-selectors`
- [ ] combine with `postcss-modules-scope`
- [x] remove pure mode
- [x] remove selectors consistency checking
- [ ] add warnings about using already declared identifier

## scope
- [ ] rename to `postcss-icss-compose` if independent splitting will be possible

## values
- [ ] disallow values names started with dot and hash. (`.5s`, `#hash`)
- [ ] this can introduce ability to replace local classes and ids correctly (cross modules will be possible for theming).

## lint
- [ ] add pure mode checking
- [ ] add selectors consistency checking

/cc @michael-ciniawsky @evilebottnawi @sullenor @outpunk @sokra

**Comment by frenzzy** [comment]
> remove local/global block behavior (`:global { .selector {} }`)

but why?

**Comment by TrySound** [comment]
It can't be resolved with postcss plugins.
